-- copied and slightly adapted from https://github.com/LunarVim/Neovim-from-scratch
require "nvimConf.options"
require "nvimConf.keymaps"
require "nvimConf.colorscheme"
require "nvimConf.autocommands"
require "pluginsConf.plugins"
require "pluginsConf.cmp"
require "pluginsConf.lsp"
require "pluginsConf.telescope"
require "pluginsConf.treesitter"
require "pluginsConf.autopairs"
require "pluginsConf.comment"
require "pluginsConf.gitsigns"
require "pluginsConf.nvim-tree"
require "pluginsConf.lualine"
require "pluginsConf.toggleterm"
require "pluginsConf.scnvim"
-- require "pluginsConf.project"
-- require "pluginsConf.impatient"
require "pluginsConf.indentline"
-- require "pluginsConf.alpha"
require "pluginsConf.whichkey"
require "pluginsConf.truezen"
require "pluginsConf.lightspeed"
-- trouble?
